import type { Metadata } from "next";
import { EditorialImage } from "@/components/EditorialImage";
import { LionheartPreviews } from "@/components/LionheartPreviews";

export const metadata: Metadata = { title: "Lionheart", description: "Lionheart is Joel Maurice Lomnick's memoir project about family, survival, identity, faith, engineering, culture, mentorship, and becoming." };

export default function LionheartPage() { return <>
  <section className="bg-softBlack text-warmIvory"><div className="site-container grid min-h-[80vh] items-center gap-12 py-16 lg:grid-cols-[.7fr_1.3fr]"><EditorialImage filename="lionheart-cover.jpg" priority className="mx-auto w-full max-w-sm" /><div><p className="eyebrow">Lionheart</p><h1 className="display-title mt-5 font-serif">The story behind the builder.</h1><p className="prose-copy prose-copy-dark mt-7">A memoir about survival, family, identity, faith, engineering, Black belonging, culture, reinvention, mentorship, and the unfinished work of becoming.</p></div></div></section>
  <section className="editorial-section bg-paper"><div className="site-container grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><blockquote className="pull-quote">Memory does not arrive as a neat timeline. It arrives as weather, rhythm, rooms, and the people whose voices stay with us.</blockquote><div className="prose-copy space-y-5"><p>Lionheart holds the private and public parts of a life in the same frame: family and career, grief and humor, Black masculinity and tenderness, faith and doubt, technical ambition and the need to belong.</p><p>The previews below are invitations into the work, not substitutes for the full story.</p></div></div></section>
  <section className="editorial-section bg-parchment"><div className="site-container"><div className="max-w-4xl"><p className="eyebrow">Reading previews</p><h2 className="section-title mt-4">Two volumes. One life still unfolding.</h2></div><div className="mt-10"><LionheartPreviews /></div></div></section>
  <section className="editorial-section bg-richBlack text-warmIvory"><div className="site-container grid gap-10 md:grid-cols-2"><div><p className="eyebrow">Volume 1</p><h2 className="subsection-title mt-3 font-serif">Lionheart: The Joel Lomnick Story - Volume 1</h2><p className="mt-4 text-base leading-8 text-warmIvory/80">A completed memoir tracing family, survival, Rochester, RIT, engineering, faith, Black belonging, culture, and the road toward reinvention.</p></div><div><p className="eyebrow">Work in progress</p><h2 className="subsection-title mt-3 font-serif">Lionheart: The Joel Lomnick Story - Volume 2</h2><p className="mt-4 text-base leading-8 text-warmIvory/80">A continuation covering Troy, Albany, Schenectady, Richmond, brotherhood, identity, rebuilding, community service, love, and the unfinished work of becoming.</p></div></div></section>
  </>; }
